
export type PhoneCountryCode = {
  name: {
    en: string;
    fr: string;
  };
  code: string;
  dial_code: string;
};

export const phoneCountryCodes: PhoneCountryCode[] = [
  { "name": { "en": "Afghanistan", "fr": "Afghanistan" }, "code": "AF", "dial_code": "+93" },
  { "name": { "en": "Albania", "fr": "Albanie" }, "code": "AL", "dial_code": "+355" },
  { "name": { "en": "Algeria", "fr": "Algérie" }, "code": "DZ", "dial_code": "+213" },
  { "name": { "en": "Andorra", "fr": "Andorre" }, "code": "AD", "dial_code": "+376" },
  { "name": { "en": "Angola", "fr": "Angola" }, "code": "AO", "dial_code": "+244" },
  { "name": { "en": "Argentina", "fr": "Argentine" }, "code": "AR", "dial_code": "+54" },
  { "name": { "en": "Armenia", "fr": "Arménie" }, "code": "AM", "dial_code": "+374" },
  { "name": { "en": "Australia", "fr": "Australie" }, "code": "AU", "dial_code": "+61" },
  { "name": { "en": "Austria", "fr": "Autriche" }, "code": "AT", "dial_code": "+43" },
  { "name": { "en": "Azerbaijan", "fr": "Azerbaïdjan" }, "code": "AZ", "dial_code": "+994" },
  { "name": { "en": "Bahamas", "fr": "Bahamas" }, "code": "BS", "dial_code": "+1242" },
  { "name": { "en": "Bahrain", "fr": "Bahreïn" }, "code": "BH", "dial_code": "+973" },
  { "name": { "en": "Bangladesh", "fr": "Bangladesh" }, "code": "BD", "dial_code": "+880" },
  { "name": { "en": "Belarus", "fr": "Biélorussie" }, "code": "BY", "dial_code": "+375" },
  { "name": { "en": "Belgium", "fr": "Belgique" }, "code": "BE", "dial_code": "+32" },
  { "name": { "en": "Belize", "fr": "Belize" }, "code": "BZ", "dial_code": "+501" },
  { "name": { "en": "Benin", "fr": "Bénin" }, "code": "BJ", "dial_code": "+229" },
  { "name": { "en": "Bolivia", "fr": "Bolivie" }, "code": "BO", "dial_code": "+591" },
  { "name": { "en": "Bosnia and Herzegovina", "fr": "Bosnie-Herzégovine" }, "code": "BA", "dial_code": "+387" },
  { "name": { "en": "Botswana", "fr": "Botswana" }, "code": "BW", "dial_code": "+267" },
  { "name": { "en": "Brazil", "fr": "Brésil" }, "code": "BR", "dial_code": "+55" },
  { "name": { "en": "Bulgaria", "fr": "Bulgarie" }, "code": "BG", "dial_code": "+359" },
  { "name": { "en": "Burkina Faso", "fr": "Burkina Faso" }, "code": "BF", "dial_code": "+226" },
  { "name": { "en": "Cambodia", "fr": "Cambodge" }, "code": "KH", "dial_code": "+855" },
  { "name": { "en": "Cameroon", "fr": "Cameroun" }, "code": "CM", "dial_code": "+237" },
  { "name": { "en": "Canada", "fr": "Canada" }, "code": "CA", "dial_code": "+1" },
  { "name": { "en": "Central African Republic", "fr": "République centrafricaine" }, "code": "CF", "dial_code": "+236" },
  { "name": { "en": "Chad", "fr": "Tchad" }, "code": "TD", "dial_code": "+235" },
  { "name": { "en": "Chile", "fr": "Chili" }, "code": "CL", "dial_code": "+56" },
  { "name": { "en": "China", "fr": "Chine" }, "code": "CN", "dial_code": "+86" },
  { "name": { "en": "Colombia", "fr": "Colombie" }, "code": "CO", "dial_code": "+57" },
  { "name": { "en": "Congo (DRC)", "fr": "Congo (RDC)" }, "code": "CD", "dial_code": "+243" },
  { "name": { "en": "Congo (Republic)", "fr": "Congo (République)" }, "code": "CG", "dial_code": "+242" },
  { "name": { "en": "Costa Rica", "fr": "Costa Rica" }, "code": "CR", "dial_code": "+506" },
  { "name": { "en": "Côte d'Ivoire", "fr": "Côte d'Ivoire" }, "code": "CI", "dial_code": "+225" },
  { "name": { "en": "Croatia", "fr": "Croatie" }, "code": "HR", "dial_code": "+385" },
  { "name": { "en": "Cuba", "fr": "Cuba" }, "code": "CU", "dial_code": "+53" },
  { "name": { "en": "Cyprus", "fr": "Chypre" }, "code": "CY", "dial_code": "+357" },
  { "name": { "en": "Czech Republic", "fr": "République tchèque" }, "code": "CZ", "dial_code": "+420" },
  { "name": { "en": "Denmark", "fr": "Danemark" }, "code": "DK", "dial_code": "+45" },
  { "name": { "en": "Djibouti", "fr": "Djibouti" }, "code": "DJ", "dial_code": "+253" },
  { "name": { "en": "Ecuador", "fr": "Équateur" }, "code": "EC", "dial_code": "+593" },
  { "name": { "en": "Egypt", "fr": "Égypte" }, "code": "EG", "dial_code": "+20" },
  { "name": { "en": "El Salvador", "fr": "Salvador" }, "code": "SV", "dial_code": "+503" },
  { "name": { "en": "Estonia", "fr": "Estonie" }, "code": "EE", "dial_code": "+372" },
  { "name": { "en": "Ethiopia", "fr": "Éthiopie" }, "code": "ET", "dial_code": "+251" },
  { "name": { "en": "Finland", "fr": "Finlande" }, "code": "FI", "dial_code": "+358" },
  { "name": { "en": "France", "fr": "France" }, "code": "FR", "dial_code": "+33" },
  { "name": { "en": "Gabon", "fr": "Gabon" }, "code": "GA", "dial_code": "+241" },
  { "name": { "en": "Georgia", "fr": "Géorgie" }, "code": "GE", "dial_code": "+995" },
  { "name": { "en": "Germany", "fr": "Allemagne" }, "code": "DE", "dial_code": "+49" },
  { "name": { "en": "Ghana", "fr": "Ghana" }, "code": "GH", "dial_code": "+233" },
  { "name": { "en": "Greece", "fr": "Grèce" }, "code": "GR", "dial_code": "+30" },
  { "name": { "en": "Guatemala", "fr": "Guatemala" }, "code": "GT", "dial_code": "+502" },
  { "name": { "en": "Guinea", "fr": "Guinée" }, "code": "GN", "dial_code": "+224" },
  { "name": { "en": "Honduras", "fr": "Honduras" }, "code": "HN", "dial_code": "+504" },
  { "name": { "en": "Hungary", "fr": "Hongrie" }, "code": "HU", "dial_code": "+36" },
  { "name": { "en": "Iceland", "fr": "Islande" }, "code": "IS", "dial_code": "+354" },
  { "name": { "en": "India", "fr": "Inde" }, "code": "IN", "dial_code": "+91" },
  { "name": { "en": "Indonesia", "fr": "Indonésie" }, "code": "ID", "dial_code": "+62" },
  { "name": { "en": "Iran", "fr": "Iran" }, "code": "IR", "dial_code": "+98" },
  { "name": { "en": "Iraq", "fr": "Irak" }, "code": "IQ", "dial_code": "+964" },
  { "name": { "en": "Ireland", "fr": "Irlande" }, "code": "IE", "dial_code": "+353" },
  { "name": { "en": "Israel", "fr": "Israël" }, "code": "IL", "dial_code": "+972" },
  { "name": { "en": "Italy", "fr": "Italie" }, "code": "IT", "dial_code": "+39" },
  { "name": { "en": "Jamaica", "fr": "Jamaïque" }, "code": "JM", "dial_code": "+1876" },
  { "name": { "en": "Japan", "fr": "Japon" }, "code": "JP", "dial_code": "+81" },
  { "name": { "en": "Jordan", "fr": "Jordanie" }, "code": "JO", "dial_code": "+962" },
  { "name": { "en": "Kazakhstan", "fr": "Kazakhstan" }, "code": "KZ", "dial_code": "+7" },
  { "name": { "en": "Kenya", "fr": "Kenya" }, "code": "KE", "dial_code": "+254" },
  { "name": { "en": "Kuwait", "fr": "Koweït" }, "code": "KW", "dial_code": "+965" },
  { "name": { "en": "Latvia", "fr": "Lettonie" }, "code": "LV", "dial_code": "+371" },
  { "name": { "en": "Lebanon", "fr": "Liban" }, "code": "LB", "dial_code": "+961" },
  { "name": { "en": "Liberia", "fr": "Libéria" }, "code": "LR", "dial_code": "+231" },
  { "name": { "en": "Libya", "fr": "Libye" }, "code": "LY", "dial_code": "+218" },
  { "name": { "en": "Lithuania", "fr": "Lituanie" }, "code": "LT", "dial_code": "+370" },
  { "name": { "en": "Luxembourg", "fr": "Luxembourg" }, "code": "LU", "dial_code": "+352" },
  { "name": { "en": "Madagascar", "fr": "Madagascar" }, "code": "MG", "dial_code": "+261" },
  { "name": { "en": "Malaysia", "fr": "Malaisie" }, "code": "MY", "dial_code": "+60" },
  { "name": { "en": "Mali", "fr": "Mali" }, "code": "ML", "dial_code": "+223" },
  { "name": { "en": "Malta", "fr": "Malte" }, "code": "MT", "dial_code": "+356" },
  { "name": { "en": "Mexico", "fr": "Mexique" }, "code": "MX", "dial_code": "+52" },
  { "name": { "en": "Moldova", "fr": "Moldavie" }, "code": "MD", "dial_code": "+373" },
  { "name": { "en": "Monaco", "fr": "Monaco" }, "code": "MC", "dial_code": "+377" },
  { "name": { "en": "Mongolia", "fr": "Mongolie" }, "code": "MN", "dial_code": "+976" },
  { "name": { "en": "Montenegro", "fr": "Monténégro" }, "code": "ME", "dial_code": "+382" },
  { "name": { "en": "Morocco", "fr": "Maroc" }, "code": "MA", "dial_code": "+212" },
  { "name": { "en": "Mozambique", "fr": "Mozambique" }, "code": "MZ", "dial_code": "+258" },
  { "name": { "en": "Myanmar (Burma)", "fr": "Myanmar (Birmanie)" }, "code": "MM", "dial_code": "+95" },
  { "name": { "en": "Namibia", "fr": "Namibie" }, "code": "NA", "dial_code": "+264" },
  { "name": { "en": "Nepal", "fr": "Népal" }, "code": "NP", "dial_code": "+977" },
  { "name": { "en": "Netherlands", "fr": "Pays-Bas" }, "code": "NL", "dial_code": "+31" },
  { "name": { "en": "New Zealand", "fr": "Nouvelle-Zélande" }, "code": "NZ", "dial_code": "+64" },
  { "name": { "en": "Nicaragua", "fr": "Nicaragua" }, "code": "NI", "dial_code": "+505" },
  { "name": { "en": "Niger", "fr": "Niger" }, "code": "NE", "dial_code": "+227" },
  { "name": { "en": "Nigeria", "fr": "Nigéria" }, "code": "NG", "dial_code": "+234" },
  { "name": { "en": "North Macedonia", "fr": "Macédoine du Nord" }, "code": "MK", "dial_code": "+389" },
  { "name": { "en": "Norway", "fr": "Norvège" }, "code": "NO", "dial_code": "+47" },
  { "name": { "en": "Oman", "fr": "Oman" }, "code": "OM", "dial_code": "+968" },
  { "name": { "en": "Pakistan", "fr": "Pakistan" }, "code": "PK", "dial_code": "+92" },
  { "name": { "en": "Panama", "fr": "Panama" }, "code": "PA", "dial_code": "+507" },
  { "name": { "en": "Paraguay", "fr": "Paraguay" }, "code": "PY", "dial_code": "+595" },
  { "name": { "en": "Peru", "fr": "Pérou" }, "code": "PE", "dial_code": "+51" },
  { "name": { "en": "Philippines", "fr": "Philippines" }, "code": "PH", "dial_code": "+63" },
  { "name": { "en": "Poland", "fr": "Pologne" }, "code": "PL", "dial_code": "+48" },
  { "name": { "en": "Portugal", "fr": "Portugal" }, "code": "PT", "dial_code": "+351" },
  { "name": { "en": "Qatar", "fr": "Qatar" }, "code": "QA", "dial_code": "+974" },
  { "name": { "en": "Romania", "fr": "Roumanie" }, "code": "RO", "dial_code": "+40" },
  { "name": { "en": "Russia", "fr": "Russie" }, "code": "RU", "dial_code": "+7" },
  { "name": { "en": "Rwanda", "fr": "Rwanda" }, "code": "RW", "dial_code": "+250" },
  { "name": { "en": "Saudi Arabia", "fr": "Arabie saoudite" }, "code": "SA", "dial_code": "+966" },
  { "name": { "en": "Senegal", "fr": "Sénégal" }, "code": "SN", "dial_code": "+221" },
  { "name": { "en": "Serbia", "fr": "Serbie" }, "code": "RS", "dial_code": "+381" },
  { "name": { "en": "Singapore", "fr": "Singapour" }, "code": "SG", "dial_code": "+65" },
  { "name": { "en": "Slovakia", "fr": "Slovaquie" }, "code": "SK", "dial_code": "+421" },
  { "name": { "en": "Slovenia", "fr": "Slovénie" }, "code": "SI", "dial_code": "+386" },
  { "name": { "en": "Somalia", "fr": "Somalie" }, "code": "SO", "dial_code": "+252" },
  { "name": { "en": "South Africa", "fr": "Afrique du Sud" }, "code": "ZA", "dial_code": "+27" },
  { "name": { "en": "South Korea", "fr": "Corée du Sud" }, "code": "KR", "dial_code": "+82" },
  { "name": { "en": "Spain", "fr": "Espagne" }, "code": "ES", "dial_code": "+34" },
  { "name": { "en": "Sri Lanka", "fr": "Sri Lanka" }, "code": "LK", "dial_code": "+94" },
  { "name": { "en": "Sudan", "fr": "Soudan" }, "code": "SD", "dial_code": "+249" },
  { "name": { "en": "Sweden", "fr": "Suède" }, "code": "SE", "dial_code": "+46" },
  { "name": { "en": "Switzerland", "fr": "Suisse" }, "code": "CH", "dial_code": "+41" },
  { "name": { "en": "Taiwan", "fr": "Taïwan" }, "code": "TW", "dial_code": "+886" },
  { "name": { "en": "Tanzania", "fr": "Tanzanie" }, "code": "TZ", "dial_code": "+255" },
  { "name": { "en": "Thailand", "fr": "Thaïlande" }, "code": "TH", "dial_code": "+66" },
  { "name": { "en": "Togo", "fr": "Togo" }, "code": "TG", "dial_code": "+228" },
  { "name": { "en": "Tunisia", "fr": "Tunisie" }, "code": "TN", "dial_code": "+216" },
  { "name": { "en": "Turkey", "fr": "Turquie" }, "code": "TR", "dial_code": "+90" },
  { "name": { "en": "Uganda", "fr": "Ouganda" }, "code": "UG", "dial_code": "+256" },
  { "name": { "en": "Ukraine", "fr": "Ukraine" }, "code": "UA", "dial_code": "+380" },
  { "name": { "en": "United Arab Emirates", "fr": "Émirats arabes unis" }, "code": "AE", "dial_code": "+971" },
  { "name": { "en": "United Kingdom", "fr": "Royaume-Uni" }, "code": "GB", "dial_code": "+44" },
  { "name": { "en": "United States", "fr": "États-Unis" }, "code": "US", "dial_code": "+1" },
  { "name": { "en": "Uruguay", "fr": "Uruguay" }, "code": "UY", "dial_code": "+598" },
  { "name": { "en": "Uzbekistan", "fr": "Ouzbékistan" }, "code": "UZ", "dial_code": "+998" },
  { "name": { "en": "Venezuela", "fr": "Venezuela" }, "code": "VE", "dial_code": "+58" },
  { "name": { "en": "Vietnam", "fr": "Viêt Nam" }, "code": "VN", "dial_code": "+84" },
  { "name": { "en": "Yemen", "fr": "Yémen" }, "code": "YE", "dial_code": "+967" },
  { "name": { "en": "Zambia", "fr": "Zambie" }, "code": "ZM", "dial_code": "+260" },
  { "name": { "en": "Zimbabwe", "fr": "Zimbabwe" }, "code": "ZW", "dial_code": "+263" }
];
