import "server-only";

import type { VerifiedMarketOpportunity } from "@/lib/ivory-coast-market";

// Short original summaries of vacancies published by the named employers.
// Opportunities without a stated deadline expire from Yahnu's public watch
// fourteen days after verification unless a content editor re-verifies them.
export const verifiedMarketOpportunities: readonly VerifiedMarketOpportunity[] = [
  {
    slug: "bic-trade-marketing-intern-abidjan",
    company: "BIC",
    title: { fr: "Stage Trade Marketing — 6 mois", en: "Trade Marketing Intern — 6 months" },
    location: { fr: "Abidjan · présentiel", en: "Abidjan · on-site" },
    workMode: "on-site",
    contract: { fr: "Stage", en: "Internship" },
    summary: {
      fr: "Une immersion de six mois au sein des activités commerciales et marketing de BIC en Côte d’Ivoire.",
      en: "A six-month placement supporting BIC’s commercial and marketing work in Côte d’Ivoire.",
    },
    tags: ["Trade marketing", "Commercial", "FMCG"],
    publishedAt: "2026-07-21",
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://careers.bic.com/BIC/job/Abidjan-Trade-Marketing-Intern-C%C3%B4te-d%26apos%3BIvoire-%28-6-months%29/1361732655/",
  },
  {
    slug: "world-bank-wbg-pioneer-operations-intern",
    company: "Groupe Banque mondiale",
    title: { fr: "WBG Pioneer — Stagiaire opérations", en: "WBG Pioneer — Operations Intern" },
    location: { fr: "Abidjan", en: "Abidjan" },
    workMode: "on-site",
    contract: { fr: "Stage", en: "Internship" },
    summary: {
      fr: "Un stage orienté opérations pour découvrir le travail de développement du Groupe Banque mondiale à Abidjan.",
      en: "An operations-focused internship providing exposure to the World Bank Group’s development work in Abidjan.",
    },
    tags: ["Operations", "Development", "Analysis"],
    publishedAt: "2026-07-21",
    deadlineAt: "2026-08-12",
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-12",
    sourceUrl: "https://worldbankgroup.csod.com/ux/ats/careersite/1/home/requisition/37729?c=worldbankgroup",
  },
  {
    slug: "totalenergies-young-graduate-rh",
    company: "TotalEnergies Marketing Côte d’Ivoire",
    title: { fr: "Young Graduate — Ressources humaines", en: "Young Graduate — Human Resources" },
    location: { fr: "Abidjan", en: "Abidjan" },
    workMode: "on-site",
    contract: { fr: "Programme jeune diplômé · 18 mois", en: "Young graduate programme · 18 months" },
    summary: {
      fr: "Un parcours de développement pour jeune diplômé souhaitant démarrer dans les ressources humaines.",
      en: "A development programme for a recent graduate starting a career in human resources.",
    },
    tags: ["Ressources humaines", "Graduate programme", "Énergie"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://jobs.totalenergies.com/fr_FR/careers/JobDetail/YOUNG-GRADUATE-RH/75799",
  },
  {
    slug: "djamo-product-designer",
    company: "Djamo",
    title: { fr: "Product Designer", en: "Product Designer" },
    location: { fr: "Abidjan ou télétravail GMT ±3", en: "Abidjan or remote within GMT ±3" },
    workMode: "remote-flexible",
    contract: { fr: "Temps plein", en: "Full time" },
    summary: {
      fr: "Concevoir des parcours financiers simples et accessibles pour une fintech active en Côte d’Ivoire et en Afrique francophone.",
      en: "Design simple, accessible financial journeys for a fintech operating in Côte d’Ivoire and Francophone Africa.",
    },
    tags: ["Product design", "Figma", "Fintech"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://careers.djamo.com/p/046aaa230936-product-designer",
  },
  {
    slug: "djamo-penetration-tester",
    company: "Djamo",
    title: { fr: "Pentester", en: "Penetration Tester" },
    location: { fr: "Abidjan ou Dakar · remote-first", en: "Abidjan or Dakar · remote-first" },
    workMode: "remote-flexible",
    contract: { fr: "Temps plein", en: "Full time" },
    summary: {
      fr: "Renforcer la sécurité des produits et infrastructures d’une fintech africaine en forte croissance.",
      en: "Strengthen the products and infrastructure of a fast-growing African fintech.",
    },
    tags: ["Cybersécurité", "Pentest", "Fintech"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://careers.djamo.com/p/b1e7a801af06-penetration-tester",
  },
  {
    slug: "yassir-data-scientist-abidjan",
    company: "Yassir",
    title: { fr: "Data Scientist", en: "Data Scientist" },
    location: { fr: "Abidjan · hybride", en: "Abidjan · hybrid" },
    workMode: "hybrid",
    contract: { fr: "Temps plein", en: "Full time" },
    summary: {
      fr: "Mettre la donnée et les modèles au service de produits numériques utilisés à grande échelle en Afrique.",
      en: "Use data and modelling to improve digital products operating at scale across Africa.",
    },
    tags: ["Data science", "Machine learning", "Mobility"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://jobs.lever.co/Yassir/37980bd7-7725-41a9-8b88-8f3f9513cd7b",
  },
  {
    slug: "coface-charge-affaires-business-information",
    company: "Coface",
    title: { fr: "Chargé·e d’affaires — Business Information", en: "Business Development Officer — Business Information" },
    location: { fr: "Abidjan", en: "Abidjan" },
    workMode: "on-site",
    contract: { fr: "CDI", en: "Permanent contract" },
    summary: {
      fr: "Développer une activité d’information commerciale auprès d’entreprises et de décideurs en Côte d’Ivoire.",
      en: "Grow a business-information service for companies and decision-makers in Côte d’Ivoire.",
    },
    tags: ["Business development", "Information", "B2B"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://jobs.smartrecruiters.com/Coface/744000126344030-charge-e-d-affaires-business-information-",
  },
  {
    slug: "imasoft-ingenieur-developpeur-applications",
    company: "IMASOFT",
    title: { fr: "Ingénieur développeur d’applications", en: "Application Software Engineer" },
    location: { fr: "Cocody, Abidjan", en: "Cocody, Abidjan" },
    workMode: "on-site",
    contract: { fr: "CDD · 2 postes", en: "Fixed-term · 2 positions" },
    summary: {
      fr: "Concevoir et faire évoluer des applications métiers au sein d’une entreprise technologique ivoirienne.",
      en: "Build and evolve business applications within an Ivorian technology company.",
    },
    tags: ["Développement logiciel", "Applications", "Technologie"],
    verifiedAt: "2026-07-25",
    expiresAt: "2026-08-08",
    sourceUrl: "https://jobs.smartrecruiters.com/IMASOFT/744000061518856-ingenieur-developpeur-d-applications",
  },
] as const;
