
import { MainNav } from "@/components/landing/main-nav";
import { Footer } from "@/components/landing/footer";
import { useLocalization } from "@/context/localization-context";

export default function PrivacyPolicyPage() {
  const { t } = useLocalization();
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <MainNav />
      <main className="flex-1 container mx-auto py-12">
        <div className="prose lg:prose-xl max-w-none">
            <h1>{t('Privacy Policy')}</h1>
            <p>{t('Last updated')}: {t('October 26, 2023')}</p>

            <p>{t('This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.')}</p>

            <h2>{t('Interpretation and Definitions')}</h2>
            <h3>{t('Interpretation')}</h3>
            <p>{t('The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.')}</p>
            <h3>{t('Definitions')}</h3>
            <p>{t('For the purposes of this Privacy Policy:')}</p>
            <ul>
                <li><strong>{t('Account')}</strong> {t('means a unique account created for You to access our Service or parts of our Service.')}</li>
                <li><strong>{t('Company')}</strong> {t('(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Yahnu.')}</li>
                <li><strong>{t('Cookies')}</strong> {t('are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.')}</li>
                <li><strong>{t('Country')}</strong> {t('refers to: Côte d\'Ivoire')}</li>
                <li><strong>{t('Device')}</strong> {t('means any device that can access the Service such as a computer, a cellphone or a digital tablet.')}</li>
                <li><strong>{t('Personal Data')}</strong> {t('is any information that relates to an identified or identifiable individual.')}</li>
                <li><strong>{t('Service')}</strong> {t('refers to the Website.')}</li>
                <li><strong>{t('Terms and Conditions')}</strong> {t('(also referred to as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service.')}</li>
                <li><strong>{t('Third-party Social Media Service')}</strong> {t('refers to any website or any social network website through which a User can log in or create an account to use the Service.')}</li>
                <li><strong>{t('Usage Data')}</strong> {t('refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).')}</li>
                <li><strong>{t('Website')}</strong> {t('refers to Yahnu, accessible from [Your Website URL]')}</li>
                <li><strong>{t('You')}</strong> {t('means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.')}</li>
            </ul>

            <h2>{t('Collecting and Using Your Personal Data')}</h2>
            <h3>{t('Types of Data Collected')}</h3>
            <h4>{t('Personal Data')}</h4>
            <p>{t('While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:')}</p>
            <ul>
                <li>{t('Email address')}</li>
                <li>{t('First name and last name')}</li>
                <li>{t('Phone number')}</li>
                <li>{t('Address, State, Province, ZIP/Postal code, City')}</li>
                <li>{t('Usage Data')}</li>
            </ul>

            <h2>{t('Use of Your Personal Data')}</h2>
            <p>{t('The Company may use Personal Data for the following purposes:')}</p>
            <ul>
                <li>{t('To provide and maintain our Service, including to monitor the usage of our Service.')}</li>
                <li>{t('To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.')}</li>
                {/* ... Add other purposes */}
            </ul>

            <h2>{t('Changes to this Privacy Policy')}</h2>
            <p>{t('We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.')}</p>
            <p>{t('We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.')}</p>
            <p>{t('You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.')}</p>

            <h2>{t('Contact Us')}</h2>
            <p>{t('If you have any questions about this Privacy Policy, You can contact us:')}</p>
            <ul>
                <li>{t('By email')}: contact@yahnu.ci</li>
            </ul>
        </div>
      </main>
      <Footer />
    </div>
  );
}
